/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v2.ui.common;

abstract class LanguageSelector_generated extends javax.swing.JMenu implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  LanguageSelector_generated()
	{
		super();
	}
	 
	public  LanguageSelector_generated(java.lang.String string, boolean boolean0)
	{
		super(string,boolean0);
	}
	 
	public  LanguageSelector_generated(java.lang.String string)
	{
		super(string);
	}
	 
	public  LanguageSelector_generated(javax.swing.Action action)
	{
		super(action);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}