/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class CrateMateEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public CrateMateEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public CrateMateEvent(star.genetics.v1.ui.events.CrateMateEvent event)
	{
		super(event);
	}

	public CrateMateEvent(star.genetics.v1.ui.events.CrateMateRaiser raiser)
	{
		super(raiser);
	}

}