/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class CrateParentsUpdatedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CrateParentsUpdatedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  CrateParentsUpdatedEvent(star.genetics.v1.ui.events.CrateParentsUpdatedEvent event)
	{
		super( event ) ;
	}
	 
	public  CrateParentsUpdatedEvent(star.genetics.v1.ui.events.CrateParentsUpdatedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}