/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class CrateNewCrateEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  CrateNewCrateEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  CrateNewCrateEvent(star.genetics.v1.ui.events.CrateNewCrateEvent event)
	{
		super( event ) ;
	}
	 
	public  CrateNewCrateEvent(star.genetics.v1.ui.events.CrateNewCrateRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}