/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class ListItemSelectedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public ListItemSelectedEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public ListItemSelectedEvent(star.genetics.v1.ui.events.ListItemSelectedEvent event)
	{
		super(event);
	}

	public ListItemSelectedEvent(star.genetics.v1.ui.events.ListItemSelectedRaiser raiser)
	{
		super(raiser);
	}

}