/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class NextFrameEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public NextFrameEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public NextFrameEvent(star.genetics.v1.ui.events.NextFrameEvent event)
	{
		super(event);
	}

	public NextFrameEvent(star.genetics.v1.ui.events.NextFrameRaiser raiser)
	{
		super(raiser);
	}

}