/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class OrganismSelectedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  OrganismSelectedEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  OrganismSelectedEvent(star.genetics.v1.ui.events.OrganismSelectedEvent event)
	{
		super( event ) ;
	}
	 
	public  OrganismSelectedEvent(star.genetics.v1.ui.events.OrganismSelectedRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}