/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class OrganismRemoveEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public OrganismRemoveEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public OrganismRemoveEvent(star.genetics.v1.ui.events.OrganismRemoveEvent event)
	{
		super(event);
	}

	public OrganismRemoveEvent(star.genetics.v1.ui.events.OrganismRemoveRaiser raiser)
	{
		super(raiser);
	}

}