/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class ProgenySelectedEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public ProgenySelectedEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public ProgenySelectedEvent(star.genetics.v1.ui.events.ProgenySelectedEvent event)
	{
		super(event);
	}

	public ProgenySelectedEvent(star.genetics.v1.ui.events.ProgenySelectedRaiser raiser)
	{
		super(raiser);
	}

}