/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class ProgenyAddProgenyEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ProgenyAddProgenyEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ProgenyAddProgenyEvent(star.genetics.v1.ui.events.ProgenyAddProgenyEvent event)
	{
		super( event ) ;
	}
	 
	public  ProgenyAddProgenyEvent(star.genetics.v1.ui.events.ProgenyAddProgenyRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}