/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.events;

public class ShowHistoryEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ShowHistoryEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ShowHistoryEvent(star.genetics.v1.ui.events.ShowHistoryEvent event)
	{
		super( event ) ;
	}
	 
	public  ShowHistoryEvent(star.genetics.v1.ui.events.ShowHistoryRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}