/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v2.ui.yeast.common;

abstract class Sporulate_generated extends star.genetics.v2.ui.common.Button implements star.event.EventController, star.event.Listener, star.genetics.v1.ui.events.CrateMateRaiser, star.genetics.v1.ui.events.ListItemSelectedRaiser, star.genetics.v2.yeast.events.StorableExperimentRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  Sporulate_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled( star.genetics.v1.ui.events.CrateProgeniesEvent.class );
		getAdapter().addHandled( star.genetics.v1.ui.events.CrateParentsEvent.class );
	}
	 
	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}
	 
	private void eventRaisedHandles(final star.event.Event event)
	{
		if( event.getClass().getName().equals( "star.genetics.v1.ui.events.CrateProgeniesEvent" ) && event.isValid() ) 
		{
			 long start = System.nanoTime();
			
			invalidCrate( (star.genetics.v1.ui.events.CrateProgeniesRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".invalidCrate "  + ( end-start )/1000000 ); } 
		}
		if( event.getClass().getName().equals( "star.genetics.v1.ui.events.CrateParentsEvent" ) && event.isValid() ) 
		{
			 long start = System.nanoTime();
			
			validParents( (star.genetics.v1.ui.events.CrateParentsRaiser)event.getSource());
			 long end = System.nanoTime();
			 if( end - start > 500000000 ) { System.out.println( this.getClass().getName() + ".validParents "  + ( end-start )/1000000 ); } 
		}
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void invalidCrate(star.genetics.v1.ui.events.CrateProgeniesRaiser CrateProgeniesRaiser);
	 
	public void raise_CrateMateEvent()
	{
		(new star.genetics.v1.ui.events.CrateMateEvent(this)).raise();
	}
	 
	public void raise_ListItemSelectedEvent()
	{
		(new star.genetics.v1.ui.events.ListItemSelectedEvent(this)).raise();
	}
	 
	public void raise_StorableExperimentEvent()
	{
		(new star.genetics.v2.yeast.events.StorableExperimentEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled( star.genetics.v1.ui.events.CrateProgeniesEvent.class );
		getAdapter().removeHandled( star.genetics.v1.ui.events.CrateParentsEvent.class );
	}
	 
	abstract void validParents(star.genetics.v1.ui.events.CrateParentsRaiser CrateParentsRaiser);
	 
}