/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.common;

abstract class ConfigureOrganismHandler_generated extends java.lang.Object implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public ConfigureOrganismHandler_generated()
	{
		super();
	}

	public void addNotify()
	{
		getAdapter().addHandled(star.genetics.v1.ui.events.ConfigureOrganismEvent.class);
	}

	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}

	private void eventRaisedHandles(final star.event.Event event)
	{
		if (event.getClass().getName().equals("star.genetics.v1.ui.events.ConfigureOrganismEvent") && event.isValid())
		{
			long start = System.nanoTime();

			handle((star.genetics.v1.ui.events.ConfigureOrganismRaiser) event.getSource());
			long end = System.nanoTime();
			if (end - start > 500000000)
			{
				System.out.println(this.getClass().getName() + ".handle " + (end - start) / 1000000);
			}
		}
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	abstract void handle(star.genetics.v1.ui.events.ConfigureOrganismRaiser ConfigureOrganismRaiser);

	public void removeNotify()
	{
		getAdapter().removeHandled(star.genetics.v1.ui.events.ConfigureOrganismEvent.class);
	}

}