/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.common;

abstract class WebSamples_generated extends javax.swing.JDialog implements star.event.EventController, star.genetics.events.OpenModelRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  WebSamples_generated()
	{
		super();
	}
	 
	public  WebSamples_generated(java.awt.Dialog dialog, boolean boolean0)
	{
		super(dialog,boolean0);
	}
	 
	public  WebSamples_generated(java.awt.Dialog dialog, java.lang.String string, boolean boolean0, java.awt.GraphicsConfiguration graphicsConfiguration)
	{
		super(dialog,string,boolean0,graphicsConfiguration);
	}
	 
	public  WebSamples_generated(java.awt.Dialog dialog, java.lang.String string, boolean boolean0)
	{
		super(dialog,string,boolean0);
	}
	 
	public  WebSamples_generated(java.awt.Dialog dialog, java.lang.String string)
	{
		super(dialog,string);
	}
	 
	public  WebSamples_generated(java.awt.Dialog dialog)
	{
		super(dialog);
	}
	 
	public  WebSamples_generated(java.awt.Frame frame, boolean boolean0)
	{
		super(frame,boolean0);
	}
	 
	public  WebSamples_generated(java.awt.Frame frame, java.lang.String string, boolean boolean0, java.awt.GraphicsConfiguration graphicsConfiguration)
	{
		super(frame,string,boolean0,graphicsConfiguration);
	}
	 
	public  WebSamples_generated(java.awt.Frame frame, java.lang.String string, boolean boolean0)
	{
		super(frame,string,boolean0);
	}
	 
	public  WebSamples_generated(java.awt.Frame frame, java.lang.String string)
	{
		super(frame,string);
	}
	 
	public  WebSamples_generated(java.awt.Frame frame)
	{
		super(frame);
	}
	 
	public  WebSamples_generated(java.awt.Window window, java.awt.Dialog.ModalityType modalityType)
	{
		super(window,modalityType);
	}
	 
	public  WebSamples_generated(java.awt.Window window, java.lang.String string, java.awt.Dialog.ModalityType modalityType, java.awt.GraphicsConfiguration graphicsConfiguration)
	{
		super(window,string,modalityType,graphicsConfiguration);
	}
	 
	public  WebSamples_generated(java.awt.Window window, java.lang.String string, java.awt.Dialog.ModalityType modalityType)
	{
		super(window,string,modalityType);
	}
	 
	public  WebSamples_generated(java.awt.Window window, java.lang.String string)
	{
		super(window,string);
	}
	 
	public  WebSamples_generated(java.awt.Window window)
	{
		super(window);
	}
	 
	abstract void addContent();
	 
	void addContent_SwingUtilitiesInvokeLater()
	{
		javax.swing.SwingUtilities.invokeLater(new java.lang.Runnable()
			{
			public void run() {
				addContent();
			}
		});
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	abstract void openURL();
	 
	void openURL_SwingUtilitiesInvokeLater()
	{
		javax.swing.SwingUtilities.invokeLater(new java.lang.Runnable()
			{
			public void run() {
				openURL();
			}
		});
	}
	 
	public void raise_OpenModelEvent()
	{
		(new star.genetics.events.OpenModelEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
}