/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.organism;

abstract class OrganismsPanel_generated extends javax.swing.JPanel implements star.event.EventController
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public OrganismsPanel_generated()
	{
		super();
	}

	public OrganismsPanel_generated(boolean boolean0)
	{
		super(boolean0);
	}

	public OrganismsPanel_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super(layoutManager, boolean0);
	}

	public OrganismsPanel_generated(java.awt.LayoutManager layoutManager)
	{
		super(layoutManager);
	}

	public void addNotify()
	{
		super.addNotify();
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	public void removeNotify()
	{
		super.removeNotify();
	}

}