/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.top;

abstract class Main_generated extends javax.swing.JPanel implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public Main_generated()
	{
		super();
	}

	public Main_generated(boolean boolean0)
	{
		super(boolean0);
	}

	public Main_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super(layoutManager, boolean0);
	}

	public Main_generated(java.awt.LayoutManager layoutManager)
	{
		super(layoutManager);
	}

	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.genetics.v1.ui.events.ShowHistoryEvent.class);
	}

	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}

	private void eventRaisedHandles(final star.event.Event event)
	{
		if (event.getClass().getName().equals("star.genetics.v1.ui.events.ShowHistoryEvent") && event.isValid())
		{
			long start = System.nanoTime();

			handleShowHistory((star.genetics.v1.ui.events.ShowHistoryRaiser) event.getSource());
			long end = System.nanoTime();
			if (end - start > 500000000)
			{
				System.out.println(this.getClass().getName() + ".handleShowHistory " + (end - start) / 1000000);
			}
		}
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	abstract void handleShowHistory(star.genetics.v1.ui.events.ShowHistoryRaiser ShowHistoryRaiser);

	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.genetics.v1.ui.events.ShowHistoryEvent.class);
	}

}