/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics;

abstract class Applet_generated extends javax.swing.JApplet implements star.event.EventController
{
	private star.event.Adapter adapter;
	private java.lang.Exception errorMessage;
	private java.util.prefs.Preferences preferences = loadPreferences();
	private static final long serialVersionUID = 1L;

	public Applet_generated() throws java.awt.HeadlessException
	{
		super();
	}

	public void addNotify()
	{
		super.addNotify();
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	public java.lang.Exception getErrorMessage()
	{
		return this.errorMessage;
	}

	java.util.prefs.Preferences getPreferences(java.lang.String name)
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			this.preferences = pref.getPreferences(name);
		}
		catch (plugin.PluginException ex)
		{
			ex.printStackTrace();
		}
		if (preferences == null)
		{
			return java.util.prefs.Preferences.userRoot().node(name);
		}
		return preferences;
	}

	java.util.prefs.Preferences getPreferences()
	{
		if (preferences == null)
		{
			try
			{
				plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
				this.preferences = pref.getPreferences("star.genetics.Applet");
			}
			catch (plugin.PluginException ex)
			{
				ex.printStackTrace();
			}
		}
		if (preferences == null)
		{
			return java.util.prefs.Preferences.userRoot().node("star.genetics.Applet");
		}
		return preferences;
	}

	java.util.prefs.Preferences loadPreferences()
	{
		try
		{
			plugin.preferences.Preferences pref = (plugin.preferences.Preferences) plugin.Loader.getDefaultLoader().getPlugin(plugin.preferences.Preferences.class.getName(), plugin.preferences.PreferencesImplementation.class.getName());
			java.util.Properties prop = new java.util.Properties();
			prop.load(this.getClass().getClassLoader().getResourceAsStream("resources/default.properties"));
			pref.setApplication("StarGenetics", prop);
		}
		catch (Throwable ex)
		{
			ex.printStackTrace();
		}
		return getPreferences();
	}

	public void removeNotify()
	{
		super.removeNotify();
	}

	protected void setErrorMessage(java.lang.Exception errorMessage)
	{
		this.errorMessage = errorMessage;
	}

}