/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui;

abstract class AnimationRaiser_generated extends java.lang.Object implements star.event.EventController, star.genetics.v1.ui.events.NextFrameRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public AnimationRaiser_generated()
	{
		super();
	}

	public void addNotify()
	{
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	public void raise_NextFrameEvent()
	{
		(new star.genetics.v1.ui.events.NextFrameEvent(this)).raise();
	}

	public void removeNotify()
	{
	}

}