/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.menu;

abstract class MenuBar_generated extends javax.swing.JMenuBar implements star.event.EventController, star.event.Listener
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public MenuBar_generated()
	{
		super();
	}

	public void addNotify()
	{
		super.addNotify();
		getAdapter().addHandled(star.genetics.events.OpenModelEvent.class);
	}

	public void eventRaised(final star.event.Event event)
	{
		eventRaisedHandles(event);
	}

	private void eventRaisedHandles(final star.event.Event event)
	{
		if (event.getClass().getName().equals("star.genetics.events.OpenModelEvent") && event.isValid())
		{
			long start = System.nanoTime();

			openFile((star.genetics.events.OpenModelRaiser) event.getSource());
			long end = System.nanoTime();
			if (end - start > 500000000)
			{
				System.out.println(this.getClass().getName() + ".openFile " + (end - start) / 1000000);
			}
		}
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	abstract void openFile(star.genetics.events.OpenModelRaiser OpenModelRaiser);

	public void removeNotify()
	{
		super.removeNotify();
		getAdapter().removeHandled(star.genetics.events.OpenModelEvent.class);
	}

}