/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.menu;

abstract class Problem_2_generated extends star.genetics.v2.ui.menu.MenuItem implements star.event.EventController, star.genetics.events.OpenModelRaiser
{
	private star.event.Adapter adapter;
	private java.lang.String modelFileName;
	private java.io.InputStream openModelStream;
	private static final long serialVersionUID = 1L;

	public Problem_2_generated()
	{
		super();
	}

	public void addNotify()
	{
		super.addNotify();
	}

	public star.event.Adapter getAdapter()
	{
		if (adapter == null)
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}

	public java.lang.String getModelFileName()
	{
		return this.modelFileName;
	}

	public java.io.InputStream getOpenModelStream()
	{
		return this.openModelStream;
	}

	public void raise_OpenModelEvent()
	{
		(new star.genetics.events.OpenModelEvent(this)).raise();
	}

	public void removeNotify()
	{
		super.removeNotify();
	}

	protected void setModelFileName(java.lang.String modelFileName)
	{
		this.modelFileName = modelFileName;
	}

	protected void setOpenModelStream(java.io.InputStream openModelStream)
	{
		this.openModelStream = openModelStream;
	}

}