/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v2.ui;

abstract class ModelSaver_generated extends javax.swing.JPanel implements star.event.EventController, star.genetics.events.ErrorDialogRaiser, star.genetics.events.SaveModelRaiser
{
	private star.event.Adapter adapter;
	private java.lang.Exception errorMessage;
	private java.lang.String modelFileName;
	private java.io.OutputStream saveModelStream;
	private static final long serialVersionUID = 1L;

	public  ModelSaver_generated()
	{
		super();
	}
	 
	public  ModelSaver_generated(boolean boolean0)
	{
		super(boolean0);
	}
	 
	public  ModelSaver_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super(layoutManager,boolean0);
	}
	 
	public  ModelSaver_generated(java.awt.LayoutManager layoutManager)
	{
		super(layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public java.lang.Exception getErrorMessage()
	{
		return this.errorMessage ;
	}
	 
	public java.lang.String getModelFileName()
	{
		return this.modelFileName ;
	}
	 
	public java.io.OutputStream getSaveModelStream()
	{
		return this.saveModelStream ;
	}
	 
	public void raise_ErrorDialogEvent()
	{
		(new star.genetics.events.ErrorDialogEvent(this)).raise();
	}
	 
	public void raise_SaveModelEvent()
	{
		(new star.genetics.events.SaveModelEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
	protected void setErrorMessage(java.lang.Exception errorMessage)
	{
		this.errorMessage = errorMessage ;
	}
	 
	protected void setModelFileName(java.lang.String modelFileName)
	{
		this.modelFileName = modelFileName ;
	}
	 
	protected void setSaveModelStream(java.io.OutputStream saveModelStream)
	{
		this.saveModelStream = saveModelStream ;
	}
	 
}