/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.events;

public class ErrorDialogEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ErrorDialogEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ErrorDialogEvent(star.genetics.events.ErrorDialogEvent event)
	{
		super( event ) ;
	}
	 
	public  ErrorDialogEvent(star.genetics.events.ErrorDialogRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}