/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.events;

public class LoadModelEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  LoadModelEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  LoadModelEvent(star.genetics.events.LoadModelEvent event)
	{
		super( event ) ;
	}
	 
	public  LoadModelEvent(star.genetics.events.LoadModelRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}