/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v3;

abstract class WebSocketComponent_generated extends java.lang.Object implements star.event.EventController, star.genetics.events.OpenModelRaiser, star.genetics.events.SaveModelRaiser
{
	private star.event.Adapter adapter;
	private static final long serialVersionUID = 1L;

	public  WebSocketComponent_generated()
	{
		super();
	}
	 
	public void addNotify()
	{
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	public void raise_OpenModelEvent()
	{
		(new star.genetics.events.OpenModelEvent(this)).raise();
	}
	 
	public void raise_SaveModelEvent()
	{
		(new star.genetics.events.SaveModelEvent(this)).raise();
	}
	 
	public void removeNotify()
	{
	}
	 
}