/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v2.yeast.events;

public class ReplicationExperimentAddAllEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public  ReplicationExperimentAddAllEvent(star.event.Raiser raiser, boolean valid)
	{
		super( raiser , valid ) ;
	}
	 
	public  ReplicationExperimentAddAllEvent(star.genetics.v2.yeast.events.ReplicationExperimentAddAllEvent event)
	{
		super( event ) ;
	}
	 
	public  ReplicationExperimentAddAllEvent(star.genetics.v2.yeast.events.ReplicationExperimentAddAllRaiser raiser)
	{
		super( raiser ) ;
	}
	 
}