/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v2.yeast.events;

public class StorableExperimentEvent extends star.event.Event
{
	private static final long serialVersionUID = 1L;

	public StorableExperimentEvent(star.event.Raiser raiser, boolean valid)
	{
		super(raiser, valid);
	}

	public StorableExperimentEvent(star.genetics.v2.yeast.events.StorableExperimentEvent event)
	{
		super(event);
	}

	public StorableExperimentEvent(star.genetics.v2.yeast.events.StorableExperimentRaiser raiser)
	{
		super(raiser);
	}

}