/* Generated by star.annotations.GeneratedClass, all changes will be lost */

package star.genetics.v1.ui.crate.progenies;

abstract class Progenies_generated extends javax.swing.JPanel implements star.event.EventController
{
	private star.event.Adapter adapter;
	private star.genetics.v1.ui.model.CrateModel model;
	private static final long serialVersionUID = 1L;

	public  Progenies_generated()
	{
		super();
	}
	 
	public  Progenies_generated(boolean boolean0)
	{
		super(boolean0);
	}
	 
	public  Progenies_generated(java.awt.LayoutManager layoutManager, boolean boolean0)
	{
		super(layoutManager,boolean0);
	}
	 
	public  Progenies_generated(java.awt.LayoutManager layoutManager)
	{
		super(layoutManager);
	}
	 
	public void addNotify()
	{
		super.addNotify();
	}
	 
	public star.event.Adapter getAdapter()
	{
		if( adapter == null )
		{
			adapter = new star.event.Adapter(this);
		}
		return adapter;
	}
	 
	protected star.genetics.v1.ui.model.CrateModel getModel()
	{
		return this.model ;
	}
	 
	public void removeNotify()
	{
		super.removeNotify();
	}
	 
	protected void setModel(star.genetics.v1.ui.model.CrateModel model)
	{
		this.model = model ;
	}
	 
}